name: Benchmark

on:
  push:
    branches: [main]
    tags: ["*"]

concurrency:
  group: ${{ github.ref }}-benchmark
  cancel-in-progress: true

jobs:
  benchmark:
    strategy:
      matrix:
        jvm: ["17"]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: ${{ matrix.jvm }}

      - name: Cache packages
        uses: coursier/cache-action@v6
        id: coursier-cache

      - name: Run Jmh benchmarks
        run: ./mill Alias/run bench

      - name: Get current date
        id: date
        run: |
          echo "date=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_OUTPUT

      - name: Upload benchmark results to Gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_description: Benchmark results for https://github.com/carlosedp/zio-channel/ at ${{ steps.date.outputs.date }}
          gist_file_name: jmh-result.json
          gist_id: e0eddcb77eee2eab18fb13d67eb0ead2
          file_path: out/benchmarks/runJmh.dest/jmh-result.json
          file_type: text
